---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: blackbox-exporter
  name: blackbox-exporter
spec:
  ports:
  - name: 9114-tcp
    port: 9114
    protocol: TCP
    targetPort: 9114
  selector:
    deployment: blackbox-exporter

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deployment: blackbox-exporter
  name: blackbox-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: blackbox-exporter
  template:
    metadata:
      labels:
        deployment: blackbox-exporter
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: blackbox
      - name: prometheus-tls
        secret:
          defaultMode: 420
          secretName: prometheus-tls
      - name: prometheus-proxy
        secret:
          defaultMode: 420
          secretName: prometheus-proxy
      serviceAccountName: prometheus
      initContainers:
        - name: wait-for-deployment
          image: 'registry.access.redhat.com/ubi8/ubi-minimal:8.4-208'
          resources:
            limits:
              cpu: 150m
              memory: 50Mi
            requests:
              cpu: 150m
              memory: 20Mi
          command:
            - /bin/sh
            - '-c'
            - for i in `seq 1 230`; do sleep 10; echo "Waiting for rhods-dashboard service to become available..."; if curl -s -k https://rhods-dashboard.redhat-ods-applications.svc:8443; then exit 0; fi; done; exit 1
      containers:
      - name: oauth-proxy
        args:
        - -provider=openshift
        - -https-address=:9114
        - -http-address=
        - -email-domain=*
        - -upstream=http://localhost:9115
        - -openshift-service-account=prometheus
        - '-openshift-sar={"resource": "namespaces", "verb": "get", "name": "redhat-ods-monitoring",
          "namespace": "redhat-ods-monitoring"}'
        - '-openshift-delegate-urls={"/": {"resource": "namespaces", "verb": "get",
          "name": "redhat-ods-monitoring", "namespace": "redhat-ods-monitoring"}}'
        - -tls-cert=/etc/tls/private/tls.crt
        - -tls-key=/etc/tls/private/tls.key
        - -client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token
        - -cookie-secret-file=/etc/proxy/secrets/session_secret
        - -openshift-ca=/etc/pki/tls/cert.pem
        - -openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - -client-id=system:serviceaccount:redhat-ods-monitoring:prometheus
        - -skip-auth-regex=^/metrics
        image: registry.redhat.io/openshift4/ose-oauth-proxy:v4.8
        ports:
        - containerPort: 9114
          name: https
        livenessProbe:
          httpGet:
            path: /oauth/healthz
            port: 9114
            scheme: HTTPS
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /oauth/healthz
            port: 9114
            scheme: HTTPS
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
        - mountPath: /etc/tls/private
          name: prometheus-tls
          readOnly: false
        - mountPath: /etc/proxy/secrets
          name: prometheus-proxy
          readOnly: false
      - image: quay.io/integreatly/prometheus-blackbox-exporter:v0.19.0
        name: blackbox-exporter
        args:
        - --log.level=debug
        - --config.file=/tmp/blackbox.yml
        volumeMounts:
        - name: config-volume
          mountPath: /tmp
        ports:
        - containerPort: 9115
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: 9115
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /-/healthy
            port: 9115
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
          requests:
            cpu: 50m
            memory: 50Mi
      restartPolicy: Always
      progressDeadlineSeconds: 2400
