kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cloud-resource-operator-cluster-rolebinding
subjects:
  - kind: ServiceAccount
    name: cloud-resource-operator
    namespace: redhat-ods-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloud-resource-operator-cluster-role
