apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: addon-managed-odh-catalog
  namespace: redhat-ods-operator
  # namespace: openshift-marketplace
spec:
  displayName: Red Hat OpenShift Data Science
  publisher: OSD Red Hat Addons
  # image: 'quay.io/modh/qe-catalog-source:latest'
  # image: 'quay.io/modh/qe-catalog-source:v1100-12'
  image: 'quay.io/modh/qe-catalog-source:v1.15.0-10'
  
  sourceType: grpc
