apiVersion: integreatly.org/v1alpha1
kind: Postgres
metadata:
  name: jupyterhub-db-rds
  namespace: redhat-ods-applications
  labels:
    productName: RHODS
spec:
  secretRef:
    name: jupyterhub-rds-secret
    namespace: redhat-ods-applications
  tier: development
  type: managed
