kind: Secret
apiVersion: v1
metadata:
  name: redhat-rhods-deadmanssnitch
  namespace: redhat-ods-monitoring

---
kind: Secret
apiVersion: v1
metadata:
  name: redhat-rhods-pagerduty
  namespace: redhat-ods-monitoring

---
kind: Secret
apiVersion: v1
metadata:
  name: redhat-rhods-smtp
  namespace: redhat-ods-monitoring

---
kind: Secret
apiVersion: v1
metadata:
  name: addon-managed-odh-parameters
  namespace: redhat-ods-operator
