apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: rhods-anaconda
spec:
  applications:
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: partners/anaconda
    name: anaconda-ce
  repos:
  - name: manifests
    uri: file:///opt/manifests/odh-manifests.tar.gz
  version: v1.0.0
