---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.grafana_secondary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"grafana-external"}}'
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"grafana"}}'
  name: grafana
  namespace: redhat-ods-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grafana
rules:
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: use-anyuid-scc
  namespace: redhat-ods-monitoring
rules:
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    verbs:
      - use
    resourceNames:
      - anyuid
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-sa-anyuid
  namespace: redhat-ods-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: use-anyuid-scc
subjects:
  - kind: ServiceAccount
    name: grafana
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-rb
  namespace: redhat-ods-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: grafana
subjects:
  - kind: ServiceAccount
    name: grafana
---
apiVersion: authorization.openshift.io/v1
kind: RoleBinding
metadata:
  name: grafana
  namespace: redhat-ods-monitoring
roleRef:
  name: view
subjects:
- kind: ServiceAccount
  name: grafana
  namespace: redhat-ods-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-auth-rb
  namespace: redhat-ods-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: grafana
    namespace: redhat-ods-monitoring
